package org.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-11-13T10:04:38.729+05:30
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "WsImplService",
                  wsdlLocation = "http://169.254.154.214:8090/test?wsdl",
                  targetNamespace = "http://example.org/")
public class WsImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.org/", "WsImplService");
    public final static QName WsImplPort = new QName("http://example.org/", "WsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://169.254.154.214:8090/test?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://169.254.154.214:8090/test?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsImpl
     */
    @WebEndpoint(name = "WsImplPort")
    public WsImpl getWsImplPort() {
        return super.getPort(WsImplPort, WsImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsImpl
     */
    @WebEndpoint(name = "WsImplPort")
    public WsImpl getWsImplPort(WebServiceFeature... features) {
        return super.getPort(WsImplPort, WsImpl.class, features);
    }

}
